name: gradle-test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Test environment
        required: true
        type: choice
        options:
          - stg
          - acc
          - prod
        default: stg
  # uncomment to run on schedule
  # schedule: # by default, gets last commit on default branch
  #   - cron: '0 9 * * *' # everyday at 9am UTC

env:
  AWS_DEFAULT_REGION: eu-west-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET_PATH: ${{ secrets.AWS_S3_BUCKET }}/${{ github.event.repository.name }}/${{ inputs.environment || 'stg' }} # 'stg' as default for schedule

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.0.2

    - name: Build with Gradle
      run: |
        gradle build

    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v2
      with:
        selenoid-start-arguments: |
          --browsers 'chrome'

    - name: Run Automated Tests
      run: |
        gradle web -D selenide.remote=http://localhost:4444/wd/hub

    - name: Generate allure report
      if: always()
      run: |
        docker run \
          --user root \
          -v $(pwd)/build/allure-results:/app/allure-results \
          -v $(pwd)/allure-report:/app/allure-report \
          --entrypoint /app/generateAllureReport.sh \
          frankescobar/allure-docker-service \
          0 default

    # uncomment to upload allure reports to s3
    # - name: Upload allure report to S3
    #   if: always()
    #   run: |
    #     aws s3 sync allure-report/ s3://${AWS_S3_BUCKET_PATH}/${{ github.run_number }}
    #     aws s3 sync allure-report/ s3://${AWS_S3_BUCKET_PATH}/latest
